/*
 * This Scala source file was generated by the Gradle 'init' task.
 */
package com.entrln

import akka.actor.ActorSystem
import akka.util.Timeout
import com.entrln.service.MoviesService
import org.springframework.context.annotation.AnnotationConfigApplicationContext
import scala.concurrent.ExecutionContext
import scala.language.postfixOps

/**
 *
 *
 * * Scala Web App project starter.
 * Uses:
 * - Scala.
 * - Akka/ Akka Http.
 * - Slick.
 *
 *
 *
 * todo: Improve error handling in MoviesDataActor and MoviesService. It should not return the internal error.
 * todo: Refactor code.
 * todo: Revisit timeout. Use more granular timeouts (read, insert....etc).
 * todo: Fix duplicate declarations in DatabaseActor and ApplicationConfiguration.
 *
 *
 *
 */
object App {
  private val applicationContext: AnnotationConfigApplicationContext = new AnnotationConfigApplicationContext(classOf[AppConfiguration])
  implicit val actorSystem: ActorSystem = applicationContext.getBean(classOf[ActorSystem])
  implicit val executionContext: ExecutionContext = applicationContext.getBean(classOf[ExecutionContext])
  implicit val defaultDatabaseTimeout: Timeout = applicationContext.getBean(classOf[Timeout])

  /**
   *
   * @param args : .
   */
  def main(args: Array[String]): Unit = {
    val moviesService: MoviesService = new MoviesService()
    moviesService.start()
  }
}